spring:
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties.hibernate:
      show_sql: true
      use_sql_comments: true
  datasource:
    url: 'jdbc:mysql://${MYSQL_HOST:localhost}:3306/rockpaperscissors'
    username: '${MYSQL_USER:dev}'
    password: '${MYSQL_PASSWORD:dev}'
    hikari:
      auto-commit: false
  main:
    banner-mode: log